/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.api;

import cn.lanxin.ApiException;
import cn.lanxin.models.V1OrgRoleCreateRequestBody;
import cn.lanxin.models.V1OrgRoleCreateResponse;
import cn.lanxin.models.V1OrgRoleMembersFetchResponse;
import cn.lanxin.models.V1RoleMemberCreateRequestBody;
import cn.lanxin.models.V1RoleMemberCreateResponse;
import cn.lanxin.models.V1RoleMemberDeleteRequestBody;
import cn.lanxin.models.V1RoleMemberDeleteResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RoleApi
 */
@Ignore
public class RoleApiTest {

    private final RoleApi api = new RoleApi();

    
    /**
     * 创建角色
     *
     * 创建角色
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1OrgRoleCreateTest() throws ApiException {
        String appToken = null;
        String orgid = null;
        V1OrgRoleCreateRequestBody v1OrgRoleCreateRequestBody = null;
        String userToken = null;
        V1OrgRoleCreateResponse response = api.v1OrgRoleCreate(appToken, orgid, v1OrgRoleCreateRequestBody, userToken);

        // TODO: test validations
    }
    
    /**
     * 获取应用运营者列表
     *
     * 获取对接组织里面某个角色的成员列表
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1OrgRoleMembersFetchTest() throws ApiException {
        String appToken = null;
        String orgid = null;
        String roleid = null;
        String userToken = null;
        V1OrgRoleMembersFetchResponse response = api.v1OrgRoleMembersFetch(appToken, orgid, roleid, userToken);

        // TODO: test validations
    }
    
    /**
     * 添加角色成员
     *
     * 添加角色成员
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1RoleMemberCreateTest() throws ApiException {
        String appToken = null;
        V1RoleMemberCreateRequestBody v1RoleMemberCreateRequestBody = null;
        String userToken = null;
        V1RoleMemberCreateResponse response = api.v1RoleMemberCreate(appToken, v1RoleMemberCreateRequestBody, userToken);

        // TODO: test validations
    }
    
    /**
     * 删除角色成员
     *
     * 删除角色成员
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1RoleMemberDeleteTest() throws ApiException {
        String appToken = null;
        String rolememberid = null;
        V1RoleMemberDeleteRequestBody v1RoleMemberDeleteRequestBody = null;
        String userToken = null;
        V1RoleMemberDeleteResponse response = api.v1RoleMemberDelete(appToken, rolememberid, v1RoleMemberDeleteRequestBody, userToken);

        // TODO: test validations
    }
    
}
