/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AncestorDepartment
 */

public class AncestorDepartment {
  public static final String SERIALIZED_NAME_DEPARTMENT_ID = "departmentId";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT_ID)
  private String departmentId;

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "externalId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  private String externalId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public AncestorDepartment departmentId(String departmentId) {
    
    this.departmentId = departmentId;
    return this;
  }

   /**
   * 人员所在的分支id
   * @return departmentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "人员所在的分支id")

  public String getDepartmentId() {
    return departmentId;
  }


  public void setDepartmentId(String departmentId) {
    this.departmentId = departmentId;
  }


  public AncestorDepartment externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * 部门数据源ID
   * @return externalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "部门数据源ID")

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public AncestorDepartment name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * 分支name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "分支name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AncestorDepartment ancestorDepartment = (AncestorDepartment) o;
    return Objects.equals(this.departmentId, ancestorDepartment.departmentId) &&
        Objects.equals(this.externalId, ancestorDepartment.externalId) &&
        Objects.equals(this.name, ancestorDepartment.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(departmentId, externalId, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AncestorDepartment {\n");
    sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

