/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AppRoamingOrgList
 */

public class AppRoamingOrgList {
  public static final String SERIALIZED_NAME_ORG_ID = "orgId";
  @SerializedName(SERIALIZED_NAME_ORG_ID)
  private String orgId;

  public static final String SERIALIZED_NAME_ORG_NAME = "orgName";
  @SerializedName(SERIALIZED_NAME_ORG_NAME)
  private String orgName;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private Integer state;


  public AppRoamingOrgList orgId(String orgId) {
    
    this.orgId = orgId;
    return this;
  }

   /**
   * 组织ID
   * @return orgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "组织ID")

  public String getOrgId() {
    return orgId;
  }


  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }


  public AppRoamingOrgList orgName(String orgName) {
    
    this.orgName = orgName;
    return this;
  }

   /**
   * 组织名称
   * @return orgName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "组织名称")

  public String getOrgName() {
    return orgName;
  }


  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }


  public AppRoamingOrgList state(Integer state) {
    
    this.state = state;
    return this;
  }

   /**
   * 应用对接组织状态，0-正常， 1- 已删除
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "应用对接组织状态，0-正常， 1- 已删除")

  public Integer getState() {
    return state;
  }


  public void setState(Integer state) {
    this.state = state;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppRoamingOrgList appRoamingOrgList = (AppRoamingOrgList) o;
    return Objects.equals(this.orgId, appRoamingOrgList.orgId) &&
        Objects.equals(this.orgName, appRoamingOrgList.orgName) &&
        Objects.equals(this.state, appRoamingOrgList.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orgId, orgName, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppRoamingOrgList {\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    orgName: ").append(toIndentedString(orgName)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

