/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SystemMsg
 */

public class SystemMsg {
  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private String content;

  public static final String SERIALIZED_NAME_MEDIA_ID = "mediaId";
  @SerializedName(SERIALIZED_NAME_MEDIA_ID)
  private String mediaId;


  public SystemMsg content(String content) {
    
    this.content = content;
    return this;
  }

   /**
   * 撤回消息时展示的系统消息内容（可选）
   * @return content
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "撤回消息时展示的系统消息内容（可选）")

  public String getContent() {
    return content;
  }


  public void setContent(String content) {
    this.content = content;
  }


  public SystemMsg mediaId(String mediaId) {
    
    this.mediaId = mediaId;
    return this;
  }

   /**
   * 撤回消息时展示的撤回图标的id
   * @return mediaId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "撤回消息时展示的撤回图标的id")

  public String getMediaId() {
    return mediaId;
  }


  public void setMediaId(String mediaId) {
    this.mediaId = mediaId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemMsg systemMsg = (SystemMsg) o;
    return Objects.equals(this.content, systemMsg.content) &&
        Objects.equals(this.mediaId, systemMsg.mediaId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, mediaId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemMsg {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

