/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1ChatNotificationFetchData
 */

public class V1ChatNotificationFetchData {
  public static final String SERIALIZED_NAME_NO_DISTURB = "noDisturb";
  @SerializedName(SERIALIZED_NAME_NO_DISTURB)
  private String noDisturb;


  public V1ChatNotificationFetchData noDisturb(String noDisturb) {
    
    this.noDisturb = noDisturb;
    return this;
  }

   /**
   * 免打扰标识
   * @return noDisturb
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "免打扰标识")

  public String getNoDisturb() {
    return noDisturb;
  }


  public void setNoDisturb(String noDisturb) {
    this.noDisturb = noDisturb;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ChatNotificationFetchData v1ChatNotificationFetchData = (V1ChatNotificationFetchData) o;
    return Objects.equals(this.noDisturb, v1ChatNotificationFetchData.noDisturb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(noDisturb);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ChatNotificationFetchData {\n");
    sb.append("    noDisturb: ").append(toIndentedString(noDisturb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

