/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1MessagesCreateData
 */

public class V1MessagesCreateData {
  public static final String SERIALIZED_NAME_INVALID_DEPARTMENT = "invalidDepartment";
  @SerializedName(SERIALIZED_NAME_INVALID_DEPARTMENT)
  private List<String> invalidDepartment = null;

  public static final String SERIALIZED_NAME_INVALID_STAFF = "invalidStaff";
  @SerializedName(SERIALIZED_NAME_INVALID_STAFF)
  private List<String> invalidStaff = null;

  public static final String SERIALIZED_NAME_MSG_ID = "msgId";
  @SerializedName(SERIALIZED_NAME_MSG_ID)
  private String msgId;


  public V1MessagesCreateData invalidDepartment(List<String> invalidDepartment) {
    
    this.invalidDepartment = invalidDepartment;
    return this;
  }

  public V1MessagesCreateData addInvalidDepartmentItem(String invalidDepartmentItem) {
    if (this.invalidDepartment == null) {
      this.invalidDepartment = new ArrayList<String>();
    }
    this.invalidDepartment.add(invalidDepartmentItem);
    return this;
  }

   /**
   * 请求departmentIdList列表中的分支ID 无效，无法发送
   * @return invalidDepartment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "请求departmentIdList列表中的分支ID 无效，无法发送")

  public List<String> getInvalidDepartment() {
    return invalidDepartment;
  }


  public void setInvalidDepartment(List<String> invalidDepartment) {
    this.invalidDepartment = invalidDepartment;
  }


  public V1MessagesCreateData invalidStaff(List<String> invalidStaff) {
    
    this.invalidStaff = invalidStaff;
    return this;
  }

  public V1MessagesCreateData addInvalidStaffItem(String invalidStaffItem) {
    if (this.invalidStaff == null) {
      this.invalidStaff = new ArrayList<String>();
    }
    this.invalidStaff.add(invalidStaffItem);
    return this;
  }

   /**
   * 请求staffIdList 列表中的人员ID 无效，无法发送
   * @return invalidStaff
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "请求staffIdList 列表中的人员ID 无效，无法发送")

  public List<String> getInvalidStaff() {
    return invalidStaff;
  }


  public void setInvalidStaff(List<String> invalidStaff) {
    this.invalidStaff = invalidStaff;
  }


  public V1MessagesCreateData msgId(String msgId) {
    
    this.msgId = msgId;
    return this;
  }

   /**
   * 消息标识，供其他接口查询进度使用。目前只有组织内应用支持返回消息ID，ISV应用不返回ID
   * @return msgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "消息标识，供其他接口查询进度使用。目前只有组织内应用支持返回消息ID，ISV应用不返回ID")

  public String getMsgId() {
    return msgId;
  }


  public void setMsgId(String msgId) {
    this.msgId = msgId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1MessagesCreateData v1MessagesCreateData = (V1MessagesCreateData) o;
    return Objects.equals(this.invalidDepartment, v1MessagesCreateData.invalidDepartment) &&
        Objects.equals(this.invalidStaff, v1MessagesCreateData.invalidStaff) &&
        Objects.equals(this.msgId, v1MessagesCreateData.msgId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invalidDepartment, invalidStaff, msgId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1MessagesCreateData {\n");
    sb.append("    invalidDepartment: ").append(toIndentedString(invalidDepartment)).append("\n");
    sb.append("    invalidStaff: ").append(toIndentedString(invalidStaff)).append("\n");
    sb.append("    msgId: ").append(toIndentedString(msgId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

