/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import cn.lanxin.models.ExtraFieldId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1OrgExtraFieldIdsFetchData
 */

public class V1OrgExtraFieldIdsFetchData {
  public static final String SERIALIZED_NAME_EXTRA_FIELD_IDS = "extraFieldIds";
  @SerializedName(SERIALIZED_NAME_EXTRA_FIELD_IDS)
  private List<ExtraFieldId> extraFieldIds = null;

  public static final String SERIALIZED_NAME_HAS_MORE = "hasMore";
  @SerializedName(SERIALIZED_NAME_HAS_MORE)
  private Boolean hasMore;

  public static final String SERIALIZED_NAME_LATEST_VERSION = "latestVersion";
  @SerializedName(SERIALIZED_NAME_LATEST_VERSION)
  private String latestVersion;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;


  public V1OrgExtraFieldIdsFetchData extraFieldIds(List<ExtraFieldId> extraFieldIds) {
    
    this.extraFieldIds = extraFieldIds;
    return this;
  }

  public V1OrgExtraFieldIdsFetchData addExtraFieldIdsItem(ExtraFieldId extraFieldIdsItem) {
    if (this.extraFieldIds == null) {
      this.extraFieldIds = new ArrayList<ExtraFieldId>();
    }
    this.extraFieldIds.add(extraFieldIdsItem);
    return this;
  }

   /**
   * Get extraFieldIds
   * @return extraFieldIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ExtraFieldId> getExtraFieldIds() {
    return extraFieldIds;
  }


  public void setExtraFieldIds(List<ExtraFieldId> extraFieldIds) {
    this.extraFieldIds = extraFieldIds;
  }


  public V1OrgExtraFieldIdsFetchData hasMore(Boolean hasMore) {
    
    this.hasMore = hasMore;
    return this;
  }

   /**
   * Get hasMore
   * @return hasMore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHasMore() {
    return hasMore;
  }


  public void setHasMore(Boolean hasMore) {
    this.hasMore = hasMore;
  }


  public V1OrgExtraFieldIdsFetchData latestVersion(String latestVersion) {
    
    this.latestVersion = latestVersion;
    return this;
  }

   /**
   * Get latestVersion
   * @return latestVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLatestVersion() {
    return latestVersion;
  }


  public void setLatestVersion(String latestVersion) {
    this.latestVersion = latestVersion;
  }


  public V1OrgExtraFieldIdsFetchData total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotal() {
    return total;
  }


  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1OrgExtraFieldIdsFetchData v1OrgExtraFieldIdsFetchData = (V1OrgExtraFieldIdsFetchData) o;
    return Objects.equals(this.extraFieldIds, v1OrgExtraFieldIdsFetchData.extraFieldIds) &&
        Objects.equals(this.hasMore, v1OrgExtraFieldIdsFetchData.hasMore) &&
        Objects.equals(this.latestVersion, v1OrgExtraFieldIdsFetchData.latestVersion) &&
        Objects.equals(this.total, v1OrgExtraFieldIdsFetchData.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extraFieldIds, hasMore, latestVersion, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1OrgExtraFieldIdsFetchData {\n");
    sb.append("    extraFieldIds: ").append(toIndentedString(extraFieldIds)).append("\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("    latestVersion: ").append(toIndentedString(latestVersion)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

