/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import cn.lanxin.models.Introduction;
import cn.lanxin.models.MobilePhone;
import cn.lanxin.models.Resume;
import cn.lanxin.models.UDepartment;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1StaffsCreateRequestBody
 */

public class V1StaffsCreateRequestBody {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_AVATAR_ID = "avatarId";
  @SerializedName(SERIALIZED_NAME_AVATAR_ID)
  private String avatarId;

  public static final String SERIALIZED_NAME_AVATAR_URL = "avatarUrl";
  @SerializedName(SERIALIZED_NAME_AVATAR_URL)
  private String avatarUrl;

  public static final String SERIALIZED_NAME_BIRTHDATE = "birthdate";
  @SerializedName(SERIALIZED_NAME_BIRTHDATE)
  private String birthdate;

  public static final String SERIALIZED_NAME_CAREER = "career";
  @SerializedName(SERIALIZED_NAME_CAREER)
  private List<Resume> career = null;

  public static final String SERIALIZED_NAME_DEPARTMENTS = "departments";
  @SerializedName(SERIALIZED_NAME_DEPARTMENTS)
  private List<UDepartment> departments = null;

  public static final String SERIALIZED_NAME_DISABLE_PASSWORD_RESET = "disablePasswordReset";
  @SerializedName(SERIALIZED_NAME_DISABLE_PASSWORD_RESET)
  private Boolean disablePasswordReset;

  public static final String SERIALIZED_NAME_DUTIES = "duties";
  @SerializedName(SERIALIZED_NAME_DUTIES)
  private String duties;

  public static final String SERIALIZED_NAME_EDUCATION = "education";
  @SerializedName(SERIALIZED_NAME_EDUCATION)
  private List<Resume> education = null;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_EMPLOYEE_NUMBER = "employeeNumber";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_NUMBER)
  private String employeeNumber;

  public static final String SERIALIZED_NAME_EXT_ATTR1 = "extAttr1";
  @SerializedName(SERIALIZED_NAME_EXT_ATTR1)
  private String extAttr1;

  public static final String SERIALIZED_NAME_EXT_ATTR2 = "extAttr2";
  @SerializedName(SERIALIZED_NAME_EXT_ATTR2)
  private String extAttr2;

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "externalId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  private String externalId;

  public static final String SERIALIZED_NAME_EXTRA_FIELD_SET = "extraFieldSet";
  @SerializedName(SERIALIZED_NAME_EXTRA_FIELD_SET)
  private Map<String, String> extraFieldSet = null;

  public static final String SERIALIZED_NAME_EXTRA_PHONES = "extraPhones";
  @SerializedName(SERIALIZED_NAME_EXTRA_PHONES)
  private List<MobilePhone> extraPhones = null;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  private Integer gender;

  public static final String SERIALIZED_NAME_ID_NUMBER = "idNumber";
  @SerializedName(SERIALIZED_NAME_ID_NUMBER)
  private String idNumber;

  public static final String SERIALIZED_NAME_INTRODUCTION = "introduction";
  @SerializedName(SERIALIZED_NAME_INTRODUCTION)
  private Introduction introduction;

  public static final String SERIALIZED_NAME_LOGIN_NAME = "loginName";
  @SerializedName(SERIALIZED_NAME_LOGIN_NAME)
  private String loginName;

  public static final String SERIALIZED_NAME_LOGIN_PASSWORD = "loginPassword";
  @SerializedName(SERIALIZED_NAME_LOGIN_PASSWORD)
  private String loginPassword;

  public static final String SERIALIZED_NAME_LOGIN_WAYS = "loginWays";
  @SerializedName(SERIALIZED_NAME_LOGIN_WAYS)
  private List<Integer> loginWays = null;

  public static final String SERIALIZED_NAME_MOBILE_PHONE = "mobilePhone";
  @SerializedName(SERIALIZED_NAME_MOBILE_PHONE)
  private MobilePhone mobilePhone;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NATIONALITY = "nationality";
  @SerializedName(SERIALIZED_NAME_NATIONALITY)
  private String nationality;

  public static final String SERIALIZED_NAME_NATIVE_PLACE = "nativePlace";
  @SerializedName(SERIALIZED_NAME_NATIVE_PLACE)
  private String nativePlace;

  public static final String SERIALIZED_NAME_ORG_ID = "orgId";
  @SerializedName(SERIALIZED_NAME_ORG_ID)
  private String orgId;

  public static final String SERIALIZED_NAME_PARTIES = "parties";
  @SerializedName(SERIALIZED_NAME_PARTIES)
  private String parties;

  public static final String SERIALIZED_NAME_SIGNATURE = "signature";
  @SerializedName(SERIALIZED_NAME_SIGNATURE)
  private String signature;

  public static final String SERIALIZED_NAME_SMS_INVITATION = "smsInvitation";
  @SerializedName(SERIALIZED_NAME_SMS_INVITATION)
  private Boolean smsInvitation;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Integer status;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = null;


  public V1StaffsCreateRequestBody address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * 人员(办公)地址
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "人员(办公)地址")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public V1StaffsCreateRequestBody avatarId(String avatarId) {
    
    this.avatarId = avatarId;
    return this;
  }

   /**
   * 人员在蓝信里的头像
   * @return avatarId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "人员在蓝信里的头像")

  public String getAvatarId() {
    return avatarId;
  }


  public void setAvatarId(String avatarId) {
    this.avatarId = avatarId;
  }


  public V1StaffsCreateRequestBody avatarUrl(String avatarUrl) {
    
    this.avatarUrl = avatarUrl;
    return this;
  }

   /**
   * 头像地址
   * @return avatarUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "头像地址")

  public String getAvatarUrl() {
    return avatarUrl;
  }


  public void setAvatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }


  public V1StaffsCreateRequestBody birthdate(String birthdate) {
    
    this.birthdate = birthdate;
    return this;
  }

   /**
   * 生日
   * @return birthdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "生日")

  public String getBirthdate() {
    return birthdate;
  }


  public void setBirthdate(String birthdate) {
    this.birthdate = birthdate;
  }


  public V1StaffsCreateRequestBody career(List<Resume> career) {
    
    this.career = career;
    return this;
  }

  public V1StaffsCreateRequestBody addCareerItem(Resume careerItem) {
    if (this.career == null) {
      this.career = new ArrayList<Resume>();
    }
    this.career.add(careerItem);
    return this;
  }

   /**
   * 职业
   * @return career
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "职业")

  public List<Resume> getCareer() {
    return career;
  }


  public void setCareer(List<Resume> career) {
    this.career = career;
  }


  public V1StaffsCreateRequestBody departments(List<UDepartment> departments) {
    
    this.departments = departments;
    return this;
  }

  public V1StaffsCreateRequestBody addDepartmentsItem(UDepartment departmentsItem) {
    if (this.departments == null) {
      this.departments = new ArrayList<UDepartment>();
    }
    this.departments.add(departmentsItem);
    return this;
  }

   /**
   * 部门
   * @return departments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "部门")

  public List<UDepartment> getDepartments() {
    return departments;
  }


  public void setDepartments(List<UDepartment> departments) {
    this.departments = departments;
  }


  public V1StaffsCreateRequestBody disablePasswordReset(Boolean disablePasswordReset) {
    
    this.disablePasswordReset = disablePasswordReset;
    return this;
  }

   /**
   * 账密登录方式，首次登录时是否禁用强制修改密码。 禁用 - true 不禁用 - false (默认)
   * @return disablePasswordReset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "账密登录方式，首次登录时是否禁用强制修改密码。 禁用 - true 不禁用 - false (默认)")

  public Boolean getDisablePasswordReset() {
    return disablePasswordReset;
  }


  public void setDisablePasswordReset(Boolean disablePasswordReset) {
    this.disablePasswordReset = disablePasswordReset;
  }


  public V1StaffsCreateRequestBody duties(String duties) {
    
    this.duties = duties;
    return this;
  }

   /**
   * 职务
   * @return duties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "职务")

  public String getDuties() {
    return duties;
  }


  public void setDuties(String duties) {
    this.duties = duties;
  }


  public V1StaffsCreateRequestBody education(List<Resume> education) {
    
    this.education = education;
    return this;
  }

  public V1StaffsCreateRequestBody addEducationItem(Resume educationItem) {
    if (this.education == null) {
      this.education = new ArrayList<Resume>();
    }
    this.education.add(educationItem);
    return this;
  }

   /**
   * 教育程度
   * @return education
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "教育程度")

  public List<Resume> getEducation() {
    return education;
  }


  public void setEducation(List<Resume> education) {
    this.education = education;
  }


  public V1StaffsCreateRequestBody email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * 电子邮箱地址, loginWays指定邮箱登录时不能为空
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "电子邮箱地址, loginWays指定邮箱登录时不能为空")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public V1StaffsCreateRequestBody employeeNumber(String employeeNumber) {
    
    this.employeeNumber = employeeNumber;
    return this;
  }

   /**
   * 人员号
   * @return employeeNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "人员号")

  public String getEmployeeNumber() {
    return employeeNumber;
  }


  public void setEmployeeNumber(String employeeNumber) {
    this.employeeNumber = employeeNumber;
  }


  public V1StaffsCreateRequestBody extAttr1(String extAttr1) {
    
    this.extAttr1 = extAttr1;
    return this;
  }

   /**
   * 扩展字段
   * @return extAttr1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "扩展字段")

  public String getExtAttr1() {
    return extAttr1;
  }


  public void setExtAttr1(String extAttr1) {
    this.extAttr1 = extAttr1;
  }


  public V1StaffsCreateRequestBody extAttr2(String extAttr2) {
    
    this.extAttr2 = extAttr2;
    return this;
  }

   /**
   * 扩展字段
   * @return extAttr2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "扩展字段")

  public String getExtAttr2() {
    return extAttr2;
  }


  public void setExtAttr2(String extAttr2) {
    this.extAttr2 = extAttr2;
  }


  public V1StaffsCreateRequestBody externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * 人员外部ID，组织通讯录数据源唯一标识人员的ID。注意，如果是账号密码方式登录蓝信，应该使用loginName字段。如果是手机号方式登录蓝信，又想保留组织内的人员唯一ID，可以使用该externalId 字段。externalId 和 employeeNumber类似，用于组织内人员的唯一标识。创建后不可修改，组织内必须唯一。
   * @return externalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "人员外部ID，组织通讯录数据源唯一标识人员的ID。注意，如果是账号密码方式登录蓝信，应该使用loginName字段。如果是手机号方式登录蓝信，又想保留组织内的人员唯一ID，可以使用该externalId 字段。externalId 和 employeeNumber类似，用于组织内人员的唯一标识。创建后不可修改，组织内必须唯一。")

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public V1StaffsCreateRequestBody extraFieldSet(Map<String, String> extraFieldSet) {
    
    this.extraFieldSet = extraFieldSet;
    return this;
  }

  public V1StaffsCreateRequestBody putExtraFieldSetItem(String key, String extraFieldSetItem) {
    if (this.extraFieldSet == null) {
      this.extraFieldSet = new HashMap<String, String>();
    }
    this.extraFieldSet.put(key, extraFieldSetItem);
    return this;
  }

   /**
   * 自定义扩展属性，k代表扩展字段ID，这个ID由蓝信管理后台预定义，应用可以通过以下接口获取获取组织预定义的人员扩展字段ID列表。
   * @return extraFieldSet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "自定义扩展属性，k代表扩展字段ID，这个ID由蓝信管理后台预定义，应用可以通过以下接口获取获取组织预定义的人员扩展字段ID列表。")

  public Map<String, String> getExtraFieldSet() {
    return extraFieldSet;
  }


  public void setExtraFieldSet(Map<String, String> extraFieldSet) {
    this.extraFieldSet = extraFieldSet;
  }


  public V1StaffsCreateRequestBody extraPhones(List<MobilePhone> extraPhones) {
    
    this.extraPhones = extraPhones;
    return this;
  }

  public V1StaffsCreateRequestBody addExtraPhonesItem(MobilePhone extraPhonesItem) {
    if (this.extraPhones == null) {
      this.extraPhones = new ArrayList<MobilePhone>();
    }
    this.extraPhones.add(extraPhonesItem);
    return this;
  }

   /**
   * 附加联系方式
   * @return extraPhones
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "附加联系方式")

  public List<MobilePhone> getExtraPhones() {
    return extraPhones;
  }


  public void setExtraPhones(List<MobilePhone> extraPhones) {
    this.extraPhones = extraPhones;
  }


  public V1StaffsCreateRequestBody gender(Integer gender) {
    
    this.gender = gender;
    return this;
  }

   /**
   * 性别：0-保密， 1-男， 2-女
   * @return gender
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "性别：0-保密， 1-男， 2-女")

  public Integer getGender() {
    return gender;
  }


  public void setGender(Integer gender) {
    this.gender = gender;
  }


  public V1StaffsCreateRequestBody idNumber(String idNumber) {
    
    this.idNumber = idNumber;
    return this;
  }

   /**
   * 身份证号
   * @return idNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "身份证号")

  public String getIdNumber() {
    return idNumber;
  }


  public void setIdNumber(String idNumber) {
    this.idNumber = idNumber;
  }


  public V1StaffsCreateRequestBody introduction(Introduction introduction) {
    
    this.introduction = introduction;
    return this;
  }

   /**
   * Get introduction
   * @return introduction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Introduction getIntroduction() {
    return introduction;
  }


  public void setIntroduction(Introduction introduction) {
    this.introduction = introduction;
  }


  public V1StaffsCreateRequestBody loginName(String loginName) {
    
    this.loginName = loginName;
    return this;
  }

   /**
   * 账密登录方式的登录账号，loginWays指定账密方式登录时不能为空。创建后不可修改，组织内必须唯一。
   * @return loginName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "账密登录方式的登录账号，loginWays指定账密方式登录时不能为空。创建后不可修改，组织内必须唯一。")

  public String getLoginName() {
    return loginName;
  }


  public void setLoginName(String loginName) {
    this.loginName = loginName;
  }


  public V1StaffsCreateRequestBody loginPassword(String loginPassword) {
    
    this.loginPassword = loginPassword;
    return this;
  }

   /**
   * 登录方式为账密登录时，设置账户的登录密码，不能为空，为避免密码泄漏，要求原始密码使用哈希算法计算哈希值后再填充该字段，具体哈希算法需要联系组织管理员确认(算法为组织配置，例如SHA256)。
   * @return loginPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "登录方式为账密登录时，设置账户的登录密码，不能为空，为避免密码泄漏，要求原始密码使用哈希算法计算哈希值后再填充该字段，具体哈希算法需要联系组织管理员确认(算法为组织配置，例如SHA256)。")

  public String getLoginPassword() {
    return loginPassword;
  }


  public void setLoginPassword(String loginPassword) {
    this.loginPassword = loginPassword;
  }


  public V1StaffsCreateRequestBody loginWays(List<Integer> loginWays) {
    
    this.loginWays = loginWays;
    return this;
  }

  public V1StaffsCreateRequestBody addLoginWaysItem(Integer loginWaysItem) {
    if (this.loginWays == null) {
      this.loginWays = new ArrayList<Integer>();
    }
    this.loginWays.add(loginWaysItem);
    return this;
  }

   /**
   * 蓝信登录方式：0-手机号， 1-邮箱， 2-账密。不填时默认手机号且手机号不能为空。目前一个人只支持一种登录方式。特别说明：如果指定账密登录方式时，需要通过蓝信超级管理员在对应的组织上创建一个组织标识
   * @return loginWays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "蓝信登录方式：0-手机号， 1-邮箱， 2-账密。不填时默认手机号且手机号不能为空。目前一个人只支持一种登录方式。特别说明：如果指定账密登录方式时，需要通过蓝信超级管理员在对应的组织上创建一个组织标识")

  public List<Integer> getLoginWays() {
    return loginWays;
  }


  public void setLoginWays(List<Integer> loginWays) {
    this.loginWays = loginWays;
  }


  public V1StaffsCreateRequestBody mobilePhone(MobilePhone mobilePhone) {
    
    this.mobilePhone = mobilePhone;
    return this;
  }

   /**
   * Get mobilePhone
   * @return mobilePhone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MobilePhone getMobilePhone() {
    return mobilePhone;
  }


  public void setMobilePhone(MobilePhone mobilePhone) {
    this.mobilePhone = mobilePhone;
  }


  public V1StaffsCreateRequestBody name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * 人员姓名
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "人员姓名")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1StaffsCreateRequestBody nationality(String nationality) {
    
    this.nationality = nationality;
    return this;
  }

   /**
   * 国家
   * @return nationality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "国家")

  public String getNationality() {
    return nationality;
  }


  public void setNationality(String nationality) {
    this.nationality = nationality;
  }


  public V1StaffsCreateRequestBody nativePlace(String nativePlace) {
    
    this.nativePlace = nativePlace;
    return this;
  }

   /**
   * 籍贯
   * @return nativePlace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "籍贯")

  public String getNativePlace() {
    return nativePlace;
  }


  public void setNativePlace(String nativePlace) {
    this.nativePlace = nativePlace;
  }


  public V1StaffsCreateRequestBody orgId(String orgId) {
    
    this.orgId = orgId;
    return this;
  }

   /**
   * 人员所在组织Id
   * @return orgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "人员所在组织Id")

  public String getOrgId() {
    return orgId;
  }


  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }


  public V1StaffsCreateRequestBody parties(String parties) {
    
    this.parties = parties;
    return this;
  }

   /**
   * 党派
   * @return parties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "党派")

  public String getParties() {
    return parties;
  }


  public void setParties(String parties) {
    this.parties = parties;
  }


  public V1StaffsCreateRequestBody signature(String signature) {
    
    this.signature = signature;
    return this;
  }

   /**
   * 人员个人签名
   * @return signature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "人员个人签名")

  public String getSignature() {
    return signature;
  }


  public void setSignature(String signature) {
    this.signature = signature;
  }


  public V1StaffsCreateRequestBody smsInvitation(Boolean smsInvitation) {
    
    this.smsInvitation = smsInvitation;
    return this;
  }

   /**
   * 是否发送验证码
   * @return smsInvitation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "是否发送验证码")

  public Boolean getSmsInvitation() {
    return smsInvitation;
  }


  public void setSmsInvitation(Boolean smsInvitation) {
    this.smsInvitation = smsInvitation;
  }


  public V1StaffsCreateRequestBody status(Integer status) {
    
    this.status = status;
    return this;
  }

   /**
   * 状态
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "状态")

  public Integer getStatus() {
    return status;
  }


  public void setStatus(Integer status) {
    this.status = status;
  }


  public V1StaffsCreateRequestBody tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public V1StaffsCreateRequestBody addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * 人员标签信息
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "人员标签信息")

  public List<String> getTags() {
    return tags;
  }


  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1StaffsCreateRequestBody v1StaffsCreateRequestBody = (V1StaffsCreateRequestBody) o;
    return Objects.equals(this.address, v1StaffsCreateRequestBody.address) &&
        Objects.equals(this.avatarId, v1StaffsCreateRequestBody.avatarId) &&
        Objects.equals(this.avatarUrl, v1StaffsCreateRequestBody.avatarUrl) &&
        Objects.equals(this.birthdate, v1StaffsCreateRequestBody.birthdate) &&
        Objects.equals(this.career, v1StaffsCreateRequestBody.career) &&
        Objects.equals(this.departments, v1StaffsCreateRequestBody.departments) &&
        Objects.equals(this.disablePasswordReset, v1StaffsCreateRequestBody.disablePasswordReset) &&
        Objects.equals(this.duties, v1StaffsCreateRequestBody.duties) &&
        Objects.equals(this.education, v1StaffsCreateRequestBody.education) &&
        Objects.equals(this.email, v1StaffsCreateRequestBody.email) &&
        Objects.equals(this.employeeNumber, v1StaffsCreateRequestBody.employeeNumber) &&
        Objects.equals(this.extAttr1, v1StaffsCreateRequestBody.extAttr1) &&
        Objects.equals(this.extAttr2, v1StaffsCreateRequestBody.extAttr2) &&
        Objects.equals(this.externalId, v1StaffsCreateRequestBody.externalId) &&
        Objects.equals(this.extraFieldSet, v1StaffsCreateRequestBody.extraFieldSet) &&
        Objects.equals(this.extraPhones, v1StaffsCreateRequestBody.extraPhones) &&
        Objects.equals(this.gender, v1StaffsCreateRequestBody.gender) &&
        Objects.equals(this.idNumber, v1StaffsCreateRequestBody.idNumber) &&
        Objects.equals(this.introduction, v1StaffsCreateRequestBody.introduction) &&
        Objects.equals(this.loginName, v1StaffsCreateRequestBody.loginName) &&
        Objects.equals(this.loginPassword, v1StaffsCreateRequestBody.loginPassword) &&
        Objects.equals(this.loginWays, v1StaffsCreateRequestBody.loginWays) &&
        Objects.equals(this.mobilePhone, v1StaffsCreateRequestBody.mobilePhone) &&
        Objects.equals(this.name, v1StaffsCreateRequestBody.name) &&
        Objects.equals(this.nationality, v1StaffsCreateRequestBody.nationality) &&
        Objects.equals(this.nativePlace, v1StaffsCreateRequestBody.nativePlace) &&
        Objects.equals(this.orgId, v1StaffsCreateRequestBody.orgId) &&
        Objects.equals(this.parties, v1StaffsCreateRequestBody.parties) &&
        Objects.equals(this.signature, v1StaffsCreateRequestBody.signature) &&
        Objects.equals(this.smsInvitation, v1StaffsCreateRequestBody.smsInvitation) &&
        Objects.equals(this.status, v1StaffsCreateRequestBody.status) &&
        Objects.equals(this.tags, v1StaffsCreateRequestBody.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, avatarId, avatarUrl, birthdate, career, departments, disablePasswordReset, duties, education, email, employeeNumber, extAttr1, extAttr2, externalId, extraFieldSet, extraPhones, gender, idNumber, introduction, loginName, loginPassword, loginWays, mobilePhone, name, nationality, nativePlace, orgId, parties, signature, smsInvitation, status, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1StaffsCreateRequestBody {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    avatarId: ").append(toIndentedString(avatarId)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    birthdate: ").append(toIndentedString(birthdate)).append("\n");
    sb.append("    career: ").append(toIndentedString(career)).append("\n");
    sb.append("    departments: ").append(toIndentedString(departments)).append("\n");
    sb.append("    disablePasswordReset: ").append(toIndentedString(disablePasswordReset)).append("\n");
    sb.append("    duties: ").append(toIndentedString(duties)).append("\n");
    sb.append("    education: ").append(toIndentedString(education)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    employeeNumber: ").append(toIndentedString(employeeNumber)).append("\n");
    sb.append("    extAttr1: ").append(toIndentedString(extAttr1)).append("\n");
    sb.append("    extAttr2: ").append(toIndentedString(extAttr2)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    extraFieldSet: ").append(toIndentedString(extraFieldSet)).append("\n");
    sb.append("    extraPhones: ").append(toIndentedString(extraPhones)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    idNumber: ").append(toIndentedString(idNumber)).append("\n");
    sb.append("    introduction: ").append(toIndentedString(introduction)).append("\n");
    sb.append("    loginName: ").append(toIndentedString(loginName)).append("\n");
    sb.append("    loginPassword: ").append(toIndentedString(loginPassword)).append("\n");
    sb.append("    loginWays: ").append(toIndentedString(loginWays)).append("\n");
    sb.append("    mobilePhone: ").append(toIndentedString(mobilePhone)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    nativePlace: ").append(toIndentedString(nativePlace)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    parties: ").append(toIndentedString(parties)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    smsInvitation: ").append(toIndentedString(smsInvitation)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

