/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import cn.lanxin.models.TagStaffInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1TagsFetchData
 */

public class V1TagsFetchData {
  public static final String SERIALIZED_NAME_HAS_MORE = "hasMore";
  @SerializedName(SERIALIZED_NAME_HAS_MORE)
  private Boolean hasMore;

  public static final String SERIALIZED_NAME_LATEST_VERSION = "latestVersion";
  @SerializedName(SERIALIZED_NAME_LATEST_VERSION)
  private String latestVersion;

  public static final String SERIALIZED_NAME_STAFFS = "staffs";
  @SerializedName(SERIALIZED_NAME_STAFFS)
  private List<TagStaffInfo> staffs = null;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;


  public V1TagsFetchData hasMore(Boolean hasMore) {
    
    this.hasMore = hasMore;
    return this;
  }

   /**
   * Get hasMore
   * @return hasMore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHasMore() {
    return hasMore;
  }


  public void setHasMore(Boolean hasMore) {
    this.hasMore = hasMore;
  }


  public V1TagsFetchData latestVersion(String latestVersion) {
    
    this.latestVersion = latestVersion;
    return this;
  }

   /**
   * Get latestVersion
   * @return latestVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLatestVersion() {
    return latestVersion;
  }


  public void setLatestVersion(String latestVersion) {
    this.latestVersion = latestVersion;
  }


  public V1TagsFetchData staffs(List<TagStaffInfo> staffs) {
    
    this.staffs = staffs;
    return this;
  }

  public V1TagsFetchData addStaffsItem(TagStaffInfo staffsItem) {
    if (this.staffs == null) {
      this.staffs = new ArrayList<TagStaffInfo>();
    }
    this.staffs.add(staffsItem);
    return this;
  }

   /**
   * Get staffs
   * @return staffs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<TagStaffInfo> getStaffs() {
    return staffs;
  }


  public void setStaffs(List<TagStaffInfo> staffs) {
    this.staffs = staffs;
  }


  public V1TagsFetchData total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotal() {
    return total;
  }


  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1TagsFetchData v1TagsFetchData = (V1TagsFetchData) o;
    return Objects.equals(this.hasMore, v1TagsFetchData.hasMore) &&
        Objects.equals(this.latestVersion, v1TagsFetchData.latestVersion) &&
        Objects.equals(this.staffs, v1TagsFetchData.staffs) &&
        Objects.equals(this.total, v1TagsFetchData.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasMore, latestVersion, staffs, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1TagsFetchData {\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("    latestVersion: ").append(toIndentedString(latestVersion)).append("\n");
    sb.append("    staffs: ").append(toIndentedString(staffs)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

