/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1TagGroupsUpdateRequestBody
 */

public class V1TagGroupsUpdateRequestBody {
  public static final String SERIALIZED_NAME_TAG_GROUP_NAME = "tagGroupName";
  @SerializedName(SERIALIZED_NAME_TAG_GROUP_NAME)
  private String tagGroupName;


  public V1TagGroupsUpdateRequestBody tagGroupName(String tagGroupName) {
    
    this.tagGroupName = tagGroupName;
    return this;
  }

   /**
   * 标签组的名字
   * @return tagGroupName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "标签组的名字")

  public String getTagGroupName() {
    return tagGroupName;
  }


  public void setTagGroupName(String tagGroupName) {
    this.tagGroupName = tagGroupName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1TagGroupsUpdateRequestBody v1TagGroupsUpdateRequestBody = (V1TagGroupsUpdateRequestBody) o;
    return Objects.equals(this.tagGroupName, v1TagGroupsUpdateRequestBody.tagGroupName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tagGroupName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1TagGroupsUpdateRequestBody {\n");
    sb.append("    tagGroupName: ").append(toIndentedString(tagGroupName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

