/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1TagGroupsFetchRequestBody
 */

public class V1TagGroupsFetchRequestBody {
  public static final String SERIALIZED_NAME_CATEGORY_LIST = "categoryList";
  @SerializedName(SERIALIZED_NAME_CATEGORY_LIST)
  private List<Integer> categoryList = null;

  public static final String SERIALIZED_NAME_ORG_ID = "orgId";
  @SerializedName(SERIALIZED_NAME_ORG_ID)
  private String orgId;

  public static final String SERIALIZED_NAME_TAG_GROUP_TYPE = "tagGroupType";
  @SerializedName(SERIALIZED_NAME_TAG_GROUP_TYPE)
  private String tagGroupType;


  public V1TagGroupsFetchRequestBody categoryList(List<Integer> categoryList) {
    
    this.categoryList = categoryList;
    return this;
  }

  public V1TagGroupsFetchRequestBody addCategoryListItem(Integer categoryListItem) {
    if (this.categoryList == null) {
      this.categoryList = new ArrayList<Integer>();
    }
    this.categoryList.add(categoryListItem);
    return this;
  }

   /**
   * 标签组分类。1：人员标签，2：分支标签
   * @return categoryList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "标签组分类。1：人员标签，2：分支标签")

  public List<Integer> getCategoryList() {
    return categoryList;
  }


  public void setCategoryList(List<Integer> categoryList) {
    this.categoryList = categoryList;
  }


  public V1TagGroupsFetchRequestBody orgId(String orgId) {
    
    this.orgId = orgId;
    return this;
  }

   /**
   * 组织ID
   * @return orgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "组织ID")

  public String getOrgId() {
    return orgId;
  }


  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }


  public V1TagGroupsFetchRequestBody tagGroupType(String tagGroupType) {
    
    this.tagGroupType = tagGroupType;
    return this;
  }

   /**
   * 标签组类型索引
   * @return tagGroupType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "标签组类型索引")

  public String getTagGroupType() {
    return tagGroupType;
  }


  public void setTagGroupType(String tagGroupType) {
    this.tagGroupType = tagGroupType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1TagGroupsFetchRequestBody v1TagGroupsFetchRequestBody = (V1TagGroupsFetchRequestBody) o;
    return Objects.equals(this.categoryList, v1TagGroupsFetchRequestBody.categoryList) &&
        Objects.equals(this.orgId, v1TagGroupsFetchRequestBody.orgId) &&
        Objects.equals(this.tagGroupType, v1TagGroupsFetchRequestBody.tagGroupType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryList, orgId, tagGroupType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1TagGroupsFetchRequestBody {\n");
    sb.append("    categoryList: ").append(toIndentedString(categoryList)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    tagGroupType: ").append(toIndentedString(tagGroupType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

