/*
 * LanXin+ OpenAPI
 * LanXin+ OpenAPI Platform
 *
 * 
 *
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */


package cn.lanxin.models;

import java.util.Objects;
import java.util.Arrays;
import cn.lanxin.models.StatusInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V2ChatNotificationUpdateRequestBody
 */

public class V2ChatNotificationUpdateRequestBody {
  public static final String SERIALIZED_NAME_STATUS_LIST = "statusList";
  @SerializedName(SERIALIZED_NAME_STATUS_LIST)
  private List<StatusInfo> statusList = null;


  public V2ChatNotificationUpdateRequestBody statusList(List<StatusInfo> statusList) {
    
    this.statusList = statusList;
    return this;
  }

  public V2ChatNotificationUpdateRequestBody addStatusListItem(StatusInfo statusListItem) {
    if (this.statusList == null) {
      this.statusList = new ArrayList<StatusInfo>();
    }
    this.statusList.add(statusListItem);
    return this;
  }

   /**
   * Get statusList
   * @return statusList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<StatusInfo> getStatusList() {
    return statusList;
  }


  public void setStatusList(List<StatusInfo> statusList) {
    this.statusList = statusList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2ChatNotificationUpdateRequestBody v2ChatNotificationUpdateRequestBody = (V2ChatNotificationUpdateRequestBody) o;
    return Objects.equals(this.statusList, v2ChatNotificationUpdateRequestBody.statusList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2ChatNotificationUpdateRequestBody {\n");
    sb.append("    statusList: ").append(toIndentedString(statusList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

